## 初始化配置至配置服务及初始化本服务数据库
preJob:
  # job 超时时间
  timeout: 1200
  # 工具 jar 包镜像库地址
  image: registry.cn-shanghai.aliyuncs.com/c7n/dbtool:0.8.0
  preInitDB:
    # 是否初始化本服务数据库
    enabled: true
    datasource:
      # 本服务数据库相关信息，端口号结尾，不要加/或者数据库名
      url: jdbc:mysql://localhost:3306?useUnicode=true&characterEncoding=utf-8&useSSL=false&useInformationSchema=true&remarks=true&serverTimezone=Asia/Shanghai
      username: username
      password: password

## 实例运行数量
replicaCount: 1

## 设置默认的 image、imageTag 和 imagePullPolicy。
image:
  repository: registry.cn-shanghai.aliyuncs.com/c7n/hzero-iam
  tag: ~
  pullPolicy: IfNotPresent

## Deployment 更新策略
deploymentUpdate:
  type: RollingUpdate
  maxUnavailable: 0
  maxSurge: 100%

## Pod 优先级设置
## ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
##
priorityClassName: ""

## Pod 节点分配
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}
tolerations: []
affinity: {}

## 给 Pod 附加的 annotations
podAnnotations: {}

## ## Pod 附加的 labels
podLabels: {}

## 实例运行时的环境变量
env:
  open:
    # 是否启用数据权限屏蔽
    HZERO_ENABLE_DATA_PERMISSION: true
    # 是否刷新密码策略到缓存
    HZERO_START_INIT_PASSWORD_POPLICY: true
    # 是否初始化三方登陆方式到缓存
    HZERO_START_INIT_OPEN_LOGIN_WAY: true
    # 是否初始化用户到缓存
    HZERO_START_INIT_USER: true
    # 是否初始化缓存LDAP
    HZERO_START_INIT_LDAP: true
    # 是否初始化缓存客户端
    HZERO_START_INIT_CLIENT: true
    # 是否初始化字段权限
    HZERO_START_INIT_FIELD_PERMISSION: true
    # 初始化导入表，第一次启动服务的时候需开启此设置
    HZERO_IMPORT_INIT_TABLE: false
    # 测试时禁用验证码功能
    HZERO_CAPTCHA_TEST_DISABLE: false
    # 是否开启拦截，只有开启才会拦截租户的新增和更新
    TENANT_INIT_ASPECT: false
    # 清除过期权限
    HZERO_PERMISSION_CLEAN_PERMISSION: false
    # 资源匹配路径
    HZERO_RESOURCE_PATTERN: /v1/*,/hzero/*,/iam/v1/*,/iam/hzero/*,/choerodon/v1/*
    # 不需要刷新权限的服务
    HZERO_PERMISSION_SKIP_PARSE_SERVICES: register,gateway,oauth,swagger
    # 是否自动刷新服务权限
    HZERO_PERMISSION_PARSE_PERMISSION: true
    # 是否启用权限缓存
    HZERO_PERMISSION_ENABLE_PERMISSION_CACHE: true

    # 本实例服务端口
    SERVER_PORT: 8030
    # 本实例管理端口
    MANAGEMENT_SERVER_PORT: 8031

    # 注册服务地址
    EUREKA_DEFAULT_ZONE: http://register-server:8000/eureka/
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
    # 续约间隔时间，默认30秒
    EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS: 30
    # 实例故障摘除时间，默认90秒，实际是90*2=180秒，配置45就是90秒
    EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS: 45
    # 网关地址
    CHOERODON_GATEWAY_URL: http://api.example.com

    # Redis 主机地址
    SPRING_REDIS_HOST: localhost
    # Redis 端口
    SPRING_REDIS_PORT: 6379
    # Redis db
    SPRING_REDIS_DATABASE: 1

    # 数据库连接地址
    SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/iam_service?useUnicode=true&characterEncoding=utf-8&useSSL=false&useInformationSchema=true&remarks=true&serverTimezone=Asia/Shanghai
    # 数据库用户名
    SPRING_DATASOURCE_USERNAME: choerodon
    # 数据库密码
    SPRING_DATASOURCE_PASSWORD: password
    # 连接池最小空闲连接数
    SPRING_DATASOURCE_MINIMUM_IDLE: 20
    # 连接池允许的最大连接数
    SPRING_DATASOURCE_MAXIMUM_POOL_SIZE: 200
    # 等待连接池分配连接的最大时长（毫秒）
    SPRING_DATASOURCE_CONNECTION_TIMEOUT: 30000

    # 连接超时
    FEIGN_CLIENT_CONFIG_DEFAULT_CONNECT_TIMEOUT: 2000
    # 读取超时
    FEIGN_CLIENT_CONFIG_DEFAULT_READ_TIMEOUT: 5000
    HZERO_ENABLE_CACHE: false
    # 在使用URL激活注册的用户账户时，对ticket加密解密的Aes密钥
    HZERO_REGISTER_URL_ACTIVATE_AES_KEY: RVz3QWIx66c6e-MDhftkIY4UTgqZBia9weaTBJvXt4s=
    # 日志级别
    LOG_LEVEL: info
    SERVICES_FRONT_URL: http://app.example.com

    JAVA_OPTS: >-
      -Xms1024m
      -Xmx1536m

    ## Skywalking 配置参数
    # SKYWALKING_OPTS: >-
    #   -javaagent:/agent/skywalking-agent.jar
    #   -Dskywalking.agent.application_code=asgard-service
    #   -Dskywalking.agent.sample_n_per_3_secs=-1
    #   -Dskywalking.collector.backend_service=oap.skywalking:11800


## Liveness 和 Readiness 探针相关配置
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
livenessProbe:
  initialDelaySeconds: 180
  periodSeconds: 30
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 15
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3

## 资源请求和限制相关配置
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  limits:
    # cpu: 100m
    memory: 2Gi
  requests:
    # cpu: 100m
    memory: 2Gi

## 插件相关配置
plugins:
  # skywalking agent 镜像地址
  skywalkingAgentImage: registry.cn-shanghai.aliyuncs.com/c7n/skywalking-agent:6.6.0

## service 相关设置
## ref: http://kubernetes.io/docs/user-guide/services/
##
service:
  # 是否启用 service 暴露本服务
  enabled: true
  # Service 名称
  name: choerodon-iam
  # Service 类型
  type: ClusterIP
  # 指定 service 的 clusterIP
  clusterIP: ~
  # 端口设置
  ports:
    # 服务端口
    http:
      port: 8030
      nodePort: 30092
    # 管理端口
    actuator:
      port: 8031
      nodePort: 30093
  ## externalIPs 设置
  # externalIPs:
  #   - externalIp1
  annotations: {}
    # prometheus.io/scrape: 'true'
    # prometheus.io/path: '/actuator/prometheus'
  # prometheus.io/port: '8031'

## 指标收集
metrics:
  # 收集应用的指标数据路径
  path: /actuator/prometheus
  # 性能指标应用分组
  group: spring-boot

# 是否收集日志至EFK
logs:
  enabled: false
  # 日志收集格式
  parser: spring-boot